# Generated by Django 6.0.3 on 2026-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartModule', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartmodule',
            name='cartNo',
            field=models.IntegerField(default=0),
        ),
    ]
