# Generated by Django 6.0.3 on 2026-03-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderModule', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderName', models.CharField(max_length=100)),
                ('orderNo', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
