# Generated by Django 6.0.3 on 2026-04-08 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderModule', '0002_ordermodule_delete_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodule',
            name='orderName',
        ),
        migrations.RemoveField(
            model_name='ordermodule',
            name='orderNo',
        ),
        migrations.AddField(
            model_name='ordermodule',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
