# Generated by Django 6.0.3 on 2026-04-28 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderModule', '0005_alter_ordermodule_user'),
        ('productModule', '0010_alter_productmodule_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orderModule.ordermodule')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productModule.productmodule')),
            ],
        ),
    ]
