# Generated by Django 6.0.3 on 2026-05-18 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderModule', '0006_orderitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodule',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
