# Generated by Django 6.0.3 on 2026-03-25 06:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productModule', '0002_rename_adminmodule_productmodule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodule',
            name='productName',
        ),
        migrations.AddField(
            model_name='productmodule',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/'),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='name',
            field=models.CharField(default='Temporary Name', max_length=255),
        ),
        migrations.AddField(
            model_name='productmodule',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='productmodule',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
