# Generated by Django 6.0.3 on 2026-03-25 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productModule', '0003_remove_productmodule_productname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodule',
            name='category_id',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
