# Generated by Django 6.0.3 on 2026-03-30 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productModule', '0004_productmodule_category_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
    ]
