# Generated by Django 6.0.3 on 2026-03-30 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productModule', '0005_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodule',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productModule.category'),
        ),
    ]
