# Generated by Django 6.0.3 on 2026-03-31 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productModule', '0006_alter_productmodule_category_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productmodule',
            old_name='category_id',
            new_name='category',
        ),
    ]
