# Generated by Django 6.0.3 on 2026-03-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productModule', '0007_rename_category_id_productmodule_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
