# Generated by Django 6.0.3 on 2026-04-16 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productModule', '0009_alter_productmodule_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodule',
            name='name',
            field=models.CharField(default='Temporary Name', max_length=255),
        ),
    ]
